services:
  dashboard:
    build: .
    container_name: dashboard
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - dashboard-db

  dashboard-db:
    image: postgres:15
    container_name: dashboard-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Toronto
    ports:
      - "5432:5432"
    volumes:
      - dashboard_data:/var/lib/postgresql/data

volumes:
  dashboard_data:
